### PR TITLE
Prioritize boolean string values when parsing filters from URL params

### PR DESCRIPTION
**Pull request by aroc**
## What does this PR do?
It adds another check in the `getCoercionType` function to prioritize `"true"` and `"false"` strings as `Boolean` filters.

## Why?
The chances that a user wants a filter to be a `Boolean` when the `property_value` is a string that is exactly `"true"` or `"false"` is higher than the chances that they want it to remain a string.

### CODE REVIEW

**Comment by dustinlarimer** [comment]
Is this issue also stemming from this method? https://github.com/keen/explorer/issues/59

**Comment by aroc** [comment]
@dustinlarimer nope, because we don't parse Datetime's until lower down in the code here. Same function, but unrelated.

**Comment by dustinlarimer** [comment]
Right- figured it was unrelated, but perhaps possible to hit 2 in 1 shot? :)

**Comment by aroc** [comment]
Certainly possible! But I'd say let's get this in first - we have a customer impacted right now that we can make very happy.

**Comment by dustinlarimer** [comment]
👍🏻

**Comment by aroc** [comment]
Just took a look at #59 - given how we do the "is this a datetime" check, I think the best solution is the URL "type" param we spoke about. Plus it would solve this whole type thing once and for all! 🎉

**Pull request merged**
