### PR TITLE
Updated button text and added ability to close demo

### PR DESCRIPTION
**Pull request by sfalkoff**
# What's this PR do?

-Updates copy in navigation bar and call to action buttons
-Adds "close" button to Explorer Demo (when a user clicks this button, the demo closes and they return to the landing page)

# Where should the reviewer start?

-Open `index.html` in your browser to see the proposed changes

# How should this be manually tested?

-Click the `Take it for a test drive!` button inside the blue header banner to enter the Explorer Demo
-Test the close demo buttons by clicking on both `close` and `x` 

# Screenshots

When you click this button:
screen shot 2015-07-28 at 3 24 15 pm

You should return to this view:
screen shot 2015-07-28 at 3 40 46 pm

### CODE REVIEW

**Comment by sfalkoff** [comment]
@dustinlarimer @lexicography can you please take a look at these changes?

**Comment by dustinlarimer** [comment]
Sure, I would be happy to check this out today!

**Comment by sfalkoff** [comment]
Thank you, I appreciate the review!

**Comment by dustinlarimer** [comment]
:+1: looks great, nice work!

**Pull request merged**
