### PR TITLE
Upgrade to react 0.14

### PR DESCRIPTION
**Pull request by joannecheng**
## What does this PR do? How does it affect users?

This PR upgrades the React version in explorer to 0.14. This means removal of a lot of deprecated methods, especially in tests. 

You can read through [this blog](http://reactkungfu.com/2015/10/upgrading-to-react-014/) to see some examples of the changes that needed to be made in order to upgrade the React version.

## How should this be tested

* Make sure there aren't any deprecated method warnings
* Make sure all tests pass
* ???

### CODE REVIEW

**Comment by aroc** [comment]
Ok, this all looks pretty good. Two things to fix:
1) The branch will have to have master merged into it.
2) I encountered a `getDOMNode()` call that an error was thrown for. It looks to be from ReactSelect:
image

**Comment by joannecheng** [comment]
Cool, going to rebase with master, fix the new failing tests, and go through React-select.

**Comment by sfalkoff** [comment]
@joannecheng flagging one npm warning I get after installing new dependencies:

screen shot 2016-01-04 at 2 22 26 pm

 I'm seeing 6 pending checks after running the unit tests, but I don't think those are new to this PR.

**Comment by joannecheng** [comment]
@sfalkoff That warning message shows up on master too. We should probably take care of it though...

**Comment by sfalkoff** [comment]
@joannecheng ahh yes, seeing that on master, in addition to: `Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead`

**Comment by aroc** [comment]
Those are all existing issues. We should probably address them. Ideally, we should just move to `postcss` instead of `less`. And I'm not sure what the `no repository field` thing is, but likely a pretty quick update to our npm package.

**Comment by joannecheng** [comment]
@aroc @sfalkoff The "no repository field" error is fixed here: https://github.com/keen/explorer/pull/87

**Comment by aroc** [comment]
Is this ready to go? Does it need another review?

**Comment by aroc** [comment]
Ok, this is ready to merge!! :ship:

**Pull request merged**
