### PR TITLE
Remove optional host parameter from embeddable code sample

### PR DESCRIPTION
**Pull request by sfalkoff**
Resolves issue #167.

### CODE REVIEW

**Comment by aroc** [comment]
There's a space beneath the `readKey` in the embed code as of this change.

image

**Comment by joannecheng** [comment]
👍

**Comment by sfalkoff** [comment]
Thanks @aroc. PR updated. Spacing should be good now!

**Comment by sfalkoff** [comment]
Thanks @joannecheng!

**Pull request merged**
