### PR TITLE
Improve CSS transitions and add Favicon

### PR DESCRIPTION
**Pull request by psgs**
Hello!

This pull request improves the use of CSS transitions so that, when the "test drive" button is hovered upon, it becomes fully highlighted at the same moment as the explorer-wrapper finishes scaling outwards.
An underline has also been added to the website's main navbar links, that appears when each link is hovered upon.

---

keentransition

---

Other additions include the implementation of the Keen IO favicon, as well as a change in the target of the navbar-brand link.

It is awesome to see Keen's data explorer being open sourced :smiley: 

Thankyou,
psgs :palm_tree:

### CODE REVIEW

**Comment by dustinlarimer** [comment]
@psgs thanks for putting so much time into this! The CSS transition and formatting improvements is great, though we're not looking to change the logo link. If you don't mind pulling that commit (eba4889) out, I would be more than happy to merge. Thanks again!

**Comment by psgs** [comment]
Hello @dustinlarimer,

Thanks for checking out this pull request! I have reverted the logo link change in commit 0ff4989
. If there are any other changes you would like me to make, please don't hesitate to let me know :smile:

**Comment by dustinlarimer** [comment]
:+1: thank you so much!

**Comment by psgs** [comment]
No problem @dustinlarimer :smiley: 
Thanks for merging this pull request :+1:

**Pull request merged**
